= 2016-09-12 Exam Exercises 
:icons: font
:sectnums:
:sectnumlevels: 2
:pi: pass:q[[.literal]##π##]
:sigma: pass:q[[.literal]##σ##]
:r: pass:q[[.literal]##r##]
:X: ⨝
:and: ∧

****
The following exercises and their solutions were originally authored by _Professor Maria de Marsico_, for the "Basi di Dati" exam session on September, the 12^th^, 2016.

Their translation is ongoing.

****

== Relational Algebra

[.exercise]
--
Consider a database with the following schema, describing *athletes appearances and medals at the 2016 Summer Olympics*:

[source, subs="verbatim, quotes"]
----
ATHLETE ([underline]##Name##, [underline]##Surname##, Nationality, BirthDate)
APPEARANCE ([underline]##Name##, [underline]##Surname##, [underline]##SportEvent##)
MEDAL ([underline]##Name##, [underline]##Surname##, [underline]##SportEvent##, GSB)
----

[NOTE]
====
* The set of each relation's underlined attributes indicates its *key*
* `APPEARANCE` describes which sporting events athletes took part in
* `MEDAL` determines which kind of medal athletes have won, one of **G**old, **S**ilver or **B**ronze
====

Write *relational algebra expressions* for the following queries:

1. Find the `Name`, `Surname` and `Nationality` of the athletes who were born before 1995 and who took part in the 100m freestyle swimming event, recorded as "100mFS".

2. Find the sport events where Chinese atheletes participated but didn't win a medal.
--

=== Answer

Start by identifying the relations that contain needed data. Two of them are required, as:

* `ATHLETE` holds athletes`' nationalities
* `APPEARANCE` describes athletes`' presence in sport events

NOTE: ``APPEARANCE```'s key implies that each athlete can participate in multiple events.

[.answer]
--
The easiest query consist of:

1. performing a *natural join* between `ATHLETE` and `APPEARANCE`, which share `Name` and `Surname`
2. *selecting* the resulting tuples whose `BirthDate` and `SportEvent` meet the desired criteria
3. *projecting* the `Name`, `Surname` and `Nationality` on the previous relation

[.relational-algebra]
{pi}[.ras]##Name, Surname, Nationality## ({sigma}[.ras]##BirthDate<01-01-1995 {and} SportEvent=100mFS## (ATHLETE {X} APPEARANCE))

A more _efficient_ query would entail selecting the relevant tuples _before_ joining relations:

[.relational-algebra]
{pi}[.ras]##Name, Surname, Nationality## ({sigma}[.ras]##BirthDate<01-01-1995## ATHLETE {X} {sigma}[.ras]##SportEvent=100mFS## APPEARANCE)
--

=== Answer

Tackle this class of problems by relying on *set differences*. 

The three relations will be included in the query as they all contain relevant data:

* `ATHLETE` includes `Nationality`
* `MEDAL` determines which athletes won a medal, their kind is though irrelevant
* `APPEARANCE` is essential to tell which athletes participated without winning medals

[.answer]
--
Find the Chinese athletes who took part in sport events:

[.relational-algebra]
{r}~1~ = {sigma}[.ras]##Nationality=Chinese## ATHLETE {X} APPEARANCE

Find the Chinese athletes who won a medal:

[.relational-algebra]
{r}~2~ = {sigma}[.ras]##Nationality=Chinese## ATHLETE {X} MEDAL

*Project* both relations on `Name`, `Surname` and `SportEvent` so that they are compatible and free of unnecessary attributes. Then *remove* {r}~2~ from {r}~1~ to obtain the set of Chinese athletes, who took part in events, but didn't win any medal. 

[.relational-algebra]
{r} = {pi}[.ras]##Name, Surname, SportEvent## ({r}~1~) - {pi}[.ras]##Name, Surname, SportEvent## ({r}~2~)

Obtain the data that was initially requested, with a final *projection*:

[.relational-algebra]
{pi}[.ras]##SportEvent## ({r})
--

Assume that the original instruction was different and read:

* Find the sporting events where Chinese athletes failed to win medals.

[.answer]
--
This kind of query should be addressed with *subtractions*. Find sport events where Chinese athletes won a medal:

[.relational-algebra]
{r}~2~ = {sigma}[.ras]##Nationality=Chinese## ATHLETE {X} MEDAL

Then remove {r}~2~ from all the athletes`' appearances, while *projecting* on `SportEvent` to ensure that the two relations are compatible and don't include unnecessary attributes:

[.relational-algebra]
{pi}[.ras]##SportEvent## APPEARANCES - {pi}[.ras]##SportEvent## {r}~2~
--