
=== Exam #4

[quote]
Unendo in join ATLETA (dopo la *proiezione* sulla nazionalità che ci interessa) con MEDAGLIA, sappiamo per ogni atleta quali sono le specialità in cui ha vinto una medaglia

Credo non si tratti di proiezione ma di selezione.

=== Exam #5

==== Issue 1

Prof. Marsico wrote:

[quote]
Trovare nome della fermata di partenza e nome della fermata di arrivo per le tratte che *non hanno corse* tra le ore 14:00 e le ore 18:00

I translated it with a messy:

[quote]
Find the `Name` of the departure stop and the final stop for each bus line that doesn't include *departures* between 14:00 and 18:00.

Una corsa puó cominciare prima dell'intervallo probito ma finire durante l'intervallo. Abbiamo solo gli orari di partenza a disposizione, mentre nel testo si parla di "corse" e non di "partenze". Ho tradotto bene l'intenzione del Prof. Marsico?

==== Issue 2

Is there a *rename* missing on page #15, in the red framed query? Relations seem incompatible.

=== Exam #7

==== Issue 1
I don't fully grasp the database design. Among the issues I can't wrap my head around:

A CALCIATORE can play multiple seasons for a team.
But CALCIATORE's `Campionato` is not part of the key, so either one `Campionato` value is stored for each footballer (can't be), or `Campionato` must be part of the key.

==== Issue 2
I think there's one "join" too many in page #6, before the last sigma.

=== Exam #8

The exercise instructs us to find orders whose quantities are higher than ten. Doesn't that exclude the value 10 itself? Shouldn't it be `<=10` instead of `<10` next to the first sigma?